"""empty message

Revision ID: e888df921786
Revises: 
Create Date: 2023-08-14 17:49:47.218020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e888df921786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_adminuser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_ginseng',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ginseng_rank', sa.Integer(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ginseng_infer',
    sa.Column('ginseng_infer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ginseng_id', sa.Integer(), nullable=True),
    sa.Column('ginseng_file_name', sa.String(length=100), nullable=True),
    sa.Column('ginseng_check_time', sa.DateTime(), nullable=True),
    sa.Column('ginseng_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ginseng_id'], ['tb_ginseng.id'], ),
    sa.PrimaryKeyConstraint('ginseng_infer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_ginseng_infer')
    op.drop_table('tb_ginseng')
    op.drop_table('tb_user')
    op.drop_table('tb_adminuser')
    # ### end Alembic commands ###
